module.exports = {
  User: require("./user.model"),
  Course: require("./course.model"),
  Cart: require("./cart.model"),
  Video: require("./video.model"),
  Audio: require("./audio.model"),
  Pdf: require("./pdf.model"),
  JobPosting: require("./job.model"),
  JobApplication: require("./jobapplication.model"),
  portfolio: require("./portfolio"),
  portfolioProject: require("./portfolioProject"),
  portfolioPhoto: require("./portfolioPhoto"),
  portfolioAchivement: require("./portfolioAchivements"),
  portfolioContact: require("./portfolioContact"),
  Payment: require("./payment.model"),
  Comment: require("./comment.model"),
  NewsLatter: require("./newslatter"),
  NewsandBlogs: require("./newsandblogs"),
  Movies: require("./movies"),
  Contact: require("./contactus"),
};
